apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-microservices-store
  name: rest-microservices-store
  namespace: spring-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-microservices-store
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-microservices-store
    spec:
      containers:
      - image: altaira/rest-microservices-store:8bb9c6158132acba9bbb54330fc88d199d3f8344
        name: rest-microservices-store
        resources: {}
status: {}
