server:
  port: 8081

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  data:
    mongodb:
      uri: mongodb://mongodb-svc.spring-cloud.svc.cluster.local:27017/stores
  rabbitmq:
    addresses: rabbitmq-svc.spring-cloud.svc.cluster.local:5672

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    region: default
    availabilityZones: 
      default: 	http://service-discovery-0.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka/, http://service-discovery-1.service-discovery-svc.spring-cloud.svc.cluster.local:8761/eureka/
logging:
  level:
    com.netflix.discovery: 'OFF'
