apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-microservices-customers
  name: rest-microservices-customers
  namespace: spring-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-microservices-customers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-microservices-customers
    spec:
      containers:
      - image: altaira/rest-microservices-customers:a02abb8f9ff2bced7a4f4cdc9f4b28aa83cb239d
        name: rest-microservices-customers
        resources: {}
status: {}
