apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-microservices-customers
  name: rest-microservices-customers
  namespace: spring-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-microservices-customers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-microservices-customers
    spec:
      containers:
      - image: altaira/rest-microservices-customers:e4ca97d381a35aa380be22ad432916c70d3464f5
        name: rest-microservices-customers
        resources: {}
status: {}
